### ISSUE TITLE
Bluebird version

### ISSUE THREAD

**Issue by benjamingr** [JonAbrams/synth#79]
Hi, I noticed you were running bluebird 1.x

I was wondering if you had any issues upgrading bluebird to 2.x (or soon 3.x) in which case if you could tell me what these issues are I'd be really happy - or you just found 1.x to be good enough?

Thanks

**Comment by JonAbrams** [comment]
I haven't looked into Bluebird >1 yet, but I haven't had any issues with 1.x.

**Comment by benjamingr** [comment]
@JonAbrams ok - thanks. Please report any pain points :)
